apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: maira-gateway
  namespace: argocd
spec:
  destination:
    namespace: maira
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
  source:
    helm:
      values: |
        replicaCount: 1
        maira:
          siteManagerAddress: "maira-sitemanager.maira"
          site: site-1
          tenant: maira.io
          namespace: default
          api_key: <generated key>
    path: .
    repoURL: https://github.com/maira-io/maira-gateway-helm-charts
    targetRevision: HEAD