apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: maira
  namespace: argocd
spec:
  destination:
    namespace: maira
    server: https://kubernetes.default.svc
  project: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
  source:
    path: .
    repoURL: https://github.com/maira-io/maira-helm-charts.git
    targetRevision: development
    helm:
      # keep values in sync with argocd/values.yaml
      values: |
        ingress:
          enabled: true
        ui:
          env:
          - name:  BASE_URL
            value: /v1
          - name:  DOMAIN
            value: maira-demo.us.auth0.com
          - name:  CLIENT_ID
            value: mtLWusyXtPIm98r7Mo2E601YKlTfhFOM
          - name: audience
            value: https://api.maira-demo.maira.io
          - name: REACT_APP_CUSTOM_SIGNUP
            value: 'yes'
          service:
            type: NodePort
        sitemanager:
          service:
            type: NodePort
        api:
          auth:
            enabled: false
          service:
            type: NodePort
          auth0_tenant: maira-demo
          default_tenant: maira.io
          default_site_key: <generated key>
          default_site: site-1
          admin_user_email: sbansal@maira.io
          slack:
            bot_server: "localhost:3000"
            socket_mode: true
            slack_bot_token: ""
            slack_app_token: ""
            log_level: info
