{{ if has "cassandra" $.Values.apps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: cassandra
  namespace: argocd
  labels:
    app: cassandra
spec:
  project: {{ $.Values.project }}
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 9.7.3
    chart: cassandra
    helm:
      values: |
        replicaCount: 1
        dbUser:
          user: cassandra_user
          existingSecret: temporal-default-store
  destination:
    name: {{ $.Values.destination }}
    namespace: {{ $.Values.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
{{ end }}