{{ if has "ingress" $.Values.apps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: ingress
  namespace: argocd
  labels:
    app: ingress
spec:
  project: {{ $.Values.project }}
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    targetRevision: 4.6.0
    chart: ingress-nginx
    helm:
      values: |
        controller:
          admissionWebhooks: 
            enabled: false
            port: 8444
  destination:
    name: {{ $.Values.destination }}
    namespace: ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
{{ end }}