{{ if has "ingress" $.Values.apps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: ingress
  namespace: argocd
  labels:
    app: ingress
spec:
  project: {{ $.Values.project }}
  source:
    repoURL: 'https://helm.nginx.com/stable'
    targetRevision: 0.16.2
    chart: nginx-ingress
    helm:
      values: |
        controller:
          service:
            externalTrafficPolicy: Cluster
          config:
            entries:
              http2: "true"
  destination:
    name: {{ $.Values.destination }}
    namespace: ingress
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
{{ end }}