{{ if has "mongodb" $.Values.apps }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: mongodb
  namespace: argocd
  labels:
    app: mongodb
spec:
  project: {{ $.Values.project }}
  source:
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 13.4.1
    chart: mongodb
    helm:
      values: |
        replicaCount: 1
        auth:
          existingSecret: temporal-default-store
  destination:
    name: {{ $.Values.destination }}
    namespace: {{ $.Values.namespace }}
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - Validate=true
    - CreateNamespace=true
{{ end }}